Separated Retriever as Base abstract class and custom post function for API
truefoundry/docs-qa-playground pull request #42
Opened 2024-02-09 05:55 UTC by S1LV3RJ1NX

- Created a base class `TFBaseRetriever` that will be inherited whenever a user needs to make a new retriever
- Added a sample `CreditCardRetriver` class that inherits `TFBaseRetriever` and `BaseRetriever` of langchain for document retrieval of credit cards
- Created a custom decorator `@retriever_post` function of FastAPI, that overrides `post` function of FastAPI, to generate API routes in the format: `/retriver/<RETRIEVER_NAME>/<func_name>`

2024-02-10 16:48 UTC, innoavator requested changes
Lets fix this PR properly to make it very clear - the PR is not easy to understand as of now.

2024-02-10 16:48 UTC, innoavator commented on backend/modules/retrievers/credit_card_retriver.bak.py
> +from typing import List
Lets remove the bak file

2024-02-10 16:48 UTC, innoavator commented on backend/modules/retrievers/base.py
> +class TFQueryEngine(ABC):
Add more documentation

2024-02-10 16:48 UTC, innoavator commented on backend/modules/retrievers/base.py
> +    def get_llm(self):
Make it fully typed

2024-02-11 05:02 UTC, S1LV3RJ1NX commented on backend/server/app.py
> +#         raise HTTPException(status_code=500, detail=str(exp))
Addressed.

2024-02-11 05:14 UTC, S1LV3RJ1NX commented on backend/modules/retrievers/base.py
> +    def get_llm(self):
Resolved.

2024-02-12 05:58 UTC, akashg3627 commented on backend/modules/retrievers/base.py
> +    @classmethod
abstractmethod
-> _get_collection, _get_vector_store_client, _get_embeddings, _get_llm 

query, get_docs

2024-02-12 09:56 UTC, akashg3627 commented on backend/modules/retrievers/base.py
> +    def _get_collection(collection_name: str) -> Collection:
```suggestion
    @abstractmethod
    def _get_collection(self,collection_name: str) -> Collection:
```

2024-02-12 11:27 UTC, innoavator requested changes

2024-02-12 11:27 UTC, innoavator commented on backend/modules/retrievers/base.py
> +    def _get_vector_store(self, collection_name: str) -> VectorStore:
get_vector_store_for_collection

2024-02-12 11:27 UTC, innoavator commented on backend/modules/retrievers/base.py
> +class BaseQueryEngine:
LangchainQueryEngine

2024-02-12 11:27 UTC, innoavator commented on backend/modules/retrievers/base.py
> +from servicefoundry.langchain import TrueFoundryChat
Let's remove this import

2024-02-12 11:27 UTC, innoavator commented on backend/modules/retrievers/base.py
> +    def _get_llm(self, model_config: LLMConfig, system_prompt: str) -> TrueFoundryChat:
import openai client - return langchain.llm

2024-02-12 11:27 UTC, innoavator commented on backend/modules/retrievers/base.py
> +    def _get_retriever(self, collection_name: str, retriever_config: RetrieverConfig) -> VectorStoreRetriever:
langchain.retriever.VectorStoreRetriever

2024-02-12 11:27 UTC, innoavator commented on backend/modules/retrievers/base.py
> +    def get_documents(input: QueryInput) -> List[Document]:
Let's remove this

2024-02-12 11:27 UTC, innoavator commented on backend/modules/retrievers/credit_card_retriver.py
> +class CredCardDocsQuery(QueryInput):
Make this DefaultRetriever

2024-02-12 11:27 UTC, innoavator commented on backend/utils/base.py
> +class RetrivalQuery(BaseModel):
Remove

2024-02-12 12:01 UTC, akashg3627 commented on backend/modules/retrievers/default_retriever.py
> +            retrieval_chain = get_retrieval_chain(
lets remove this function and directly use RetrivalQA class here

2024-02-12 13:08 UTC, akashg3627 commented on backend/modules/retrievers/base.py
> +        default="""Your task is to craft the most helpful, highly informative, accurate and comprehensive answers possible,
lets move these texts to some common constants file in src folder

2024-02-12 13:09 UTC, akashg3627 commented on backend/modules/retrievers/base.py
> +        default="""Here is the context information:\n\n'''\n{context}\n'''\n\nQuestion: {question}\nAnswer:""",
lets move these texts to some common constants file in src folder

2024-02-12 13:09 UTC, akashg3627 commented on backend/modules/retrievers/base.py
> +        """Logic for using a custom llm if any"""
```suggestion
        """Function to get langchain chat llm class"""
```

2024-02-12 14:14 UTC, akashg3627 commented on backend/modules/retrievers/base.py
> +    retrieval_chain_name: Optional[Literal["RetrievalQA"]] = Field(
not needed

2024-02-12 17:15 UTC, innoavator requested changes

2024-02-12 17:15 UTC, innoavator commented on backend/modules/retrievers/base.py
> +    model_configuration: Optional[LLMConfig | str]
Let's remove the str?

2024-02-12 17:15 UTC, innoavator commented on backend/modules/retrievers/base.py
> +    prompt_template: Optional[str] = Field(
Can we have a better default prompt?

2024-02-12 17:15 UTC, innoavator commented on backend/modules/retrievers/base.py
> +    """Base Query Engine class, this class lets you write your own retriver. All it's methods can be inherited and overridden
nit: retriever

2024-02-12 17:34 UTC, innoavator requested changes

2024-02-12 17:34 UTC, innoavator commented on backend/modules/retrievers/default_retriever.py
> +            from langchain.prompts import PromptTemplate
Can we not import within the function?

2024-02-12 17:35 UTC, innoavator requested changes

2024-02-12 17:35 UTC, innoavator commented on backend/modules/retrievers/__init__.py
> +        "DefaultRAGTool",
This should be a registry instead of adding it in a central place

2024-02-12 17:36 UTC, akashg3627 commented on backend/modules/retrievers/__init__.py
> +        "DefaultRAGTool",
Lets get this part of code deleted

2024-02-13 05:25 UTC, S1LV3RJ1NX commented on backend/modules/retrievers/__init__.py
> +        "DefaultRAGTool",
To be done later...deferred for now.

2024-02-14 14:04 UTC, closed without merging